# Generated by Django 5.2 on 2025-04-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hot_cold', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'unique_together': {('day', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('ssn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.employee')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ssn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.employee')),
                ('percentage_ownership', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
            ],
            options={
                'unique_together': {('day', 'time', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ingredient_unit', models.CharField(max_length=5)),
                ('position_number', models.PositiveSmallIntegerField()),
                ('execution_description', models.TextField()),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.inventorymanagement')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
            ],
            options={
                'unique_together': {('recipe_name', 'position_number')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit card', 'Credit Card'), ('app', 'App')], max_length=20)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
            ],
            options={
                'unique_together': {('time', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.inventorymanagement')),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.manager')),
            ],
            options={
                'unique_together': {('ssn', 'name')},
            },
        ),
    ]
