# Generated by Django 5.2 on 2025-04-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymanagement',
            name='ssn',
        ),
        migrations.DeleteModel(
            name='Manages',
        ),
    ]
