# Generated by Django 5.2.17 on 2026-08-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_inventorymanagement_ssn_delete_manages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorymanagement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
