# Generated by Django 5.2.17 on 2026-08-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='hot_cold',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], max_length=4),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('tea', 'Tea'), ('coffee', 'Coffee'), ('softdrink', 'Soft Drink')], max_length=20),
        ),
    ]
